use aon_sim::{
    Capacity, CapacityProbeProfile, CapacitySupportError, CapacitySupportProbeProfile, Energy,
    EntityId, FIXED_ONE, Rational, WireId, calculate_capacity_support_demand,
    distribute_capacity_support_demand,
};

/// Maximum number of independent capacity-support cases generated by one invocation.
pub const MAX_CAPACITY_SUPPORT_INPUT_BYTES: usize = 128;

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct CapacitySupportCoverage {
    pub zero_excess_cases: u64,
    pub active_curve_cases: u64,
    pub fractional_final_ceil_cases: u64,
    pub multi_wire_cases: u64,
    pub nonzero_remainder_cases: u64,
    pub permutation_checks: u64,
    pub monotonicity_checks: u64,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CapacitySupportCaseObservation {
    pub supported: Capacity,
    pub used: Capacity,
    pub demand: Energy,
    pub next_raw_demand: Energy,
    pub shares: Vec<(WireId, Capacity, Energy)>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CapacitySupportStage {
    Curve,
    NextRawCurve,
    Distribution,
    PermutedDistribution,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CapacitySupportInvariant {
    BoundedProfileConstruction,
    IndependentCurveOracle,
    ExcessMonotonicity,
    DistributionPermutation,
    DistributionConservation,
    DistributionOrder,
    IndependentDistributionOracle,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CapacitySupportExecutionObservation {
    KernelError {
        case_index: usize,
        stage: CapacitySupportStage,
        error: CapacitySupportError,
    },
    InvariantViolation {
        case_index: usize,
        invariant: CapacitySupportInvariant,
    },
    Completed,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CapacitySupportObservation {
    pub consumed_len: usize,
    pub generated_cases: usize,
    pub cases: Vec<CapacitySupportCaseObservation>,
    pub coverage: CapacitySupportCoverage,
    pub execution: CapacitySupportExecutionObservation,
}

impl CapacitySupportObservation {
    /// Returns a harness failure. Every generated value is deliberately bounded, so a typed
    /// arithmetic error is just as significant as a panic or an oracle disagreement here.
    pub const fn invariant_failure(&self) -> Option<&'static str> {
        match self.execution {
            CapacitySupportExecutionObservation::KernelError { .. } => {
                Some("bounded capacity-support input produced a kernel error")
            }
            CapacitySupportExecutionObservation::InvariantViolation { .. } => {
                Some("capacity-support output disagreed with an independent invariant")
            }
            CapacitySupportExecutionObservation::Completed => None,
        }
    }
}

/// Exercises the public S1-M3 capacity-support curve and distribution with bounded cases.
///
/// Each byte contributes one case. Extra values are consumed cyclically, so short inputs still
/// vary coefficients and Wire partitions while the case count stays strictly bounded. All exact
/// expectations are recomputed by a small independent `u128` rational oracle.
pub fn exercise_capacity_support(input: &[u8]) -> CapacitySupportObservation {
    let bounded = &input[..input.len().min(MAX_CAPACITY_SUPPORT_INPUT_BYTES)];
    let mut observation = CapacitySupportObservation {
        consumed_len: bounded.len(),
        generated_cases: 0,
        cases: Vec::with_capacity(bounded.len()),
        coverage: CapacitySupportCoverage::default(),
        execution: CapacitySupportExecutionObservation::Completed,
    };
    let mut cursor = CyclicBytes::new(bounded);

    for (case_index, selector) in bounded.iter().copied().enumerate() {
        let supported_whole = 1_u64 + u64::from(selector >> 4);
        let excess_quarters = u64::from(selector & 0x0f);
        let supported = Capacity(supported_whole * FIXED_ONE as u64);
        let excess = Capacity(excess_quarters * (FIXED_ONE as u64 / 4));
        let used = Capacity(supported.0 + excess.0);

        let Some(linear) = bounded_ratio(
            i64::from(cursor.next_u8() % 4),
            i64::from(1 + cursor.next_u8() % 7),
        ) else {
            return finish_invariant(
                observation,
                case_index,
                CapacitySupportInvariant::BoundedProfileConstruction,
            );
        };
        let Some(quadratic) = bounded_ratio(
            i64::from(1 + cursor.next_u8() % 4),
            i64::from(1 + cursor.next_u8() % 7),
        ) else {
            return finish_invariant(
                observation,
                case_index,
                CapacitySupportInvariant::BoundedProfileConstruction,
            );
        };
        let Some(support_power_per_ncu) = bounded_ratio(
            i64::from(1 + cursor.next_u8() % 5),
            i64::from(1 + cursor.next_u8() % 7),
        ) else {
            return finish_invariant(
                observation,
                case_index,
                CapacitySupportInvariant::BoundedProfileConstruction,
            );
        };
        let Some(support_heat_fraction) = bounded_ratio(1, 4) else {
            return finish_invariant(
                observation,
                case_index,
                CapacitySupportInvariant::BoundedProfileConstruction,
            );
        };
        let capacity = CapacityProbeProfile {
            main_core_capacity: supported_whole,
            relay_capacity: 1,
            overcap_linear_k: linear,
            overcap_quadratic_k: quadratic,
            capacity_denominator_floor: 1 + u64::from(cursor.next_u8() % 4),
            relay_offline_grace_ticks: 1,
            support_heat_fraction,
        };
        let support = CapacitySupportProbeProfile {
            support_power_per_ncu,
        };

        let demand = match calculate_capacity_support_demand(used, supported, &capacity, &support) {
            Ok(demand) => demand,
            Err(error) => {
                return finish_kernel_error(
                    observation,
                    case_index,
                    CapacitySupportStage::Curve,
                    error,
                );
            }
        };
        let (oracle, final_fraction) =
            independent_curve_oracle(used, supported, &capacity, &support);
        if demand != oracle {
            return finish_invariant(
                observation,
                case_index,
                CapacitySupportInvariant::IndependentCurveOracle,
            );
        }

        let next_used = Capacity(used.0 + 1);
        let next_raw_demand =
            match calculate_capacity_support_demand(next_used, supported, &capacity, &support) {
                Ok(demand) => demand,
                Err(error) => {
                    return finish_kernel_error(
                        observation,
                        case_index,
                        CapacitySupportStage::NextRawCurve,
                        error,
                    );
                }
            };
        if next_raw_demand < demand {
            return finish_invariant(
                observation,
                case_index,
                CapacitySupportInvariant::ExcessMonotonicity,
            );
        }

        let wire_count = 1 + usize::from(cursor.next_u8() % 4);
        let wire_lengths = partition_used_capacity(used, wire_count, &mut cursor);
        let shares = match distribute_capacity_support_demand(used, demand, &wire_lengths) {
            Ok(shares) => shares,
            Err(error) => {
                return finish_kernel_error(
                    observation,
                    case_index,
                    CapacitySupportStage::Distribution,
                    error,
                );
            }
        };
        let mut permuted = wire_lengths.clone();
        permuted.reverse();
        let permuted_shares = match distribute_capacity_support_demand(used, demand, &permuted) {
            Ok(shares) => shares,
            Err(error) => {
                return finish_kernel_error(
                    observation,
                    case_index,
                    CapacitySupportStage::PermutedDistribution,
                    error,
                );
            }
        };
        if shares != permuted_shares {
            return finish_invariant(
                observation,
                case_index,
                CapacitySupportInvariant::DistributionPermutation,
            );
        }
        if shares.iter().map(|share| share.demand().0).sum::<u64>() != demand.0 {
            return finish_invariant(
                observation,
                case_index,
                CapacitySupportInvariant::DistributionConservation,
            );
        }
        if !shares
            .windows(2)
            .all(|pair| pair[0].wire() < pair[1].wire())
        {
            return finish_invariant(
                observation,
                case_index,
                CapacitySupportInvariant::DistributionOrder,
            );
        }
        let expected_shares = independent_distribution_oracle(used, demand, &wire_lengths);
        let observed_shares = shares
            .iter()
            .map(|share| (share.wire(), share.length(), share.demand()))
            .collect::<Vec<_>>();
        if observed_shares != expected_shares {
            return finish_invariant(
                observation,
                case_index,
                CapacitySupportInvariant::IndependentDistributionOracle,
            );
        }

        observation.generated_cases += 1;
        observation.coverage.permutation_checks += 1;
        observation.coverage.monotonicity_checks += 1;
        if excess.0 == 0 {
            observation.coverage.zero_excess_cases += 1;
        } else {
            observation.coverage.active_curve_cases += 1;
        }
        if final_fraction {
            observation.coverage.fractional_final_ceil_cases += 1;
        }
        if wire_count > 1 {
            observation.coverage.multi_wire_cases += 1;
        }
        let floor_sum = wire_lengths
            .iter()
            .map(|(_, length)| {
                (u128::from(demand.0) * u128::from(length.0) / u128::from(used.0)) as u64
            })
            .sum::<u64>();
        if floor_sum < demand.0 {
            observation.coverage.nonzero_remainder_cases += 1;
        }
        observation.cases.push(CapacitySupportCaseObservation {
            supported,
            used,
            demand,
            next_raw_demand,
            shares: observed_shares,
        });
    }

    observation
}

fn finish_kernel_error(
    mut observation: CapacitySupportObservation,
    case_index: usize,
    stage: CapacitySupportStage,
    error: CapacitySupportError,
) -> CapacitySupportObservation {
    observation.execution = CapacitySupportExecutionObservation::KernelError {
        case_index,
        stage,
        error,
    };
    observation
}

fn finish_invariant(
    mut observation: CapacitySupportObservation,
    case_index: usize,
    invariant: CapacitySupportInvariant,
) -> CapacitySupportObservation {
    observation.execution = CapacitySupportExecutionObservation::InvariantViolation {
        case_index,
        invariant,
    };
    observation
}

fn bounded_ratio(numerator: i64, denominator: i64) -> Option<Rational> {
    Rational::new(numerator, denominator).ok()
}

fn partition_used_capacity(
    used: Capacity,
    count: usize,
    cursor: &mut CyclicBytes<'_>,
) -> Vec<(WireId, Capacity)> {
    let mut remaining = used.0;
    let mut result = Vec::with_capacity(count);
    for index in 0..count {
        let remaining_slots = u64::try_from(count - index - 1).unwrap_or(0);
        let length = if remaining_slots == 0 {
            remaining
        } else {
            let available = remaining - remaining_slots;
            1 + u64::from(cursor.next_u8()) % available
        };
        remaining -= length;
        result.push((
            WireId(EntityId(2 + u64::try_from(index).unwrap_or(0) * 2)),
            Capacity(length),
        ));
    }
    result
}

fn independent_curve_oracle(
    used: Capacity,
    supported: Capacity,
    capacity: &CapacityProbeProfile,
    support: &CapacitySupportProbeProfile,
) -> (Energy, bool) {
    let excess = u128::from(used.0.saturating_sub(supported.0));
    if excess == 0 {
        return (Energy(0), false);
    }
    let floor_raw = u128::from(capacity.capacity_denominator_floor) * FIXED_ONE as u128;
    let curve_denominator = u128::from(supported.0).max(floor_raw);
    let linear_n = u128::try_from(capacity.overcap_linear_k.numerator()).unwrap_or(0) * excess;
    let linear_d = u128::try_from(capacity.overcap_linear_k.denominator()).unwrap_or(1);
    let quadratic_n =
        u128::try_from(capacity.overcap_quadratic_k.numerator()).unwrap_or(0) * excess * excess;
    let quadratic_d =
        u128::try_from(capacity.overcap_quadratic_k.denominator()).unwrap_or(1) * curve_denominator;
    let curve_n = linear_n * quadratic_d + quadratic_n * linear_d;
    let curve_d = linear_d * quadratic_d;
    let support_n = u128::try_from(support.support_power_per_ncu.numerator()).unwrap_or(0);
    let support_d = u128::try_from(support.support_power_per_ncu.denominator()).unwrap_or(1);
    let numerator = curve_n * support_n;
    let denominator = curve_d * support_d * FIXED_ONE as u128;
    let quotient = numerator / denominator;
    let fractional = !numerator.is_multiple_of(denominator);
    let ceiling = quotient + u128::from(fractional);
    (
        Energy(u64::try_from(ceiling).unwrap_or(u64::MAX)),
        fractional,
    )
}

fn independent_distribution_oracle(
    used: Capacity,
    demand: Energy,
    wires: &[(WireId, Capacity)],
) -> Vec<(WireId, Capacity, Energy)> {
    let mut wires = wires.to_vec();
    wires.sort_unstable_by_key(|(wire, _)| *wire);
    let mut allocated = 0_u64;
    let mut result = wires
        .into_iter()
        .map(|(wire, length)| {
            let share = (u128::from(demand.0) * u128::from(length.0) / u128::from(used.0)) as u64;
            allocated += share;
            (wire, length, Energy(share))
        })
        .collect::<Vec<_>>();
    let remainder = usize::try_from(demand.0 - allocated).unwrap_or(0);
    for (_, _, share) in result.iter_mut().take(remainder) {
        share.0 += 1;
    }
    result
}

struct CyclicBytes<'a> {
    bytes: &'a [u8],
    cursor: usize,
}

impl<'a> CyclicBytes<'a> {
    const fn new(bytes: &'a [u8]) -> Self {
        Self { bytes, cursor: 0 }
    }

    fn next_u8(&mut self) -> u8 {
        if self.bytes.is_empty() {
            return 0;
        }
        let value = self.bytes[self.cursor % self.bytes.len()];
        self.cursor += 1;
        value
    }
}
