use aon_sim::{
    BalanceProfile, Command, CommandEnvelope, ConstructionSite, ConstructionSiteId,
    ConstructionSiteStore, ConstructionTarget, ConstructionWorkContribution, ContactAllocation,
    ContactCandidate, DamageSnapshot, DemandId, DemandKind, DestructionKind, DriveStrength,
    DriverId, ElectricalExposure, EndpointTarget, EnemyId, EnemyInitialState, Energy, EntityId,
    FIXED_ONE, Fixed, FixedAabb, FixedVec2, GateId, GatePort, GatePortRef, GateType,
    HeatContributionInput, HeatContributionKey, HeatEnergy, HostileCollider, InitialWorld,
    Integrity, InteractionHeatKind, LogicLevel, MobileId, NumericProfile, PhysicalScaleProfile,
    PlaceConstructionSiteCommand, PlaceFixedSubstrateCommand, PlaceGateCommand,
    PlaceMobileSubstrateCommand, PlaceWireCommand, PowerSourceInitialState, ProfileBundle,
    Rational, RoutingDomain, RunEndCause, RunStatus, SetExternalDriverCommand, Simulation,
    SimulationContract, SimulationError, SimulationPackage, StageFeatureSet, StateHash,
    ThermalDamageError, ThermalObjectKind, Tick, WireId, WorldInputEvent, allocate_contact_energy,
    apply_construction_work, calculate_live_wire_demand, integrate_heat,
    required_construction_work, resolve_damage,
};

/// Maximum number of independent S1-M4 public-kernel cases generated by one invocation.
pub const MAX_S1M4_KERNEL_INPUT_BYTES: usize = 128;

/// Maximum number of stateful S1-M4 public-runtime scenarios generated by one invocation.
pub const MAX_S1M4_RUNTIME_INPUT_BYTES: usize = 12;

const WU: i64 = FIXED_ONE;
const CIRCUIT_PITCH: i64 = 16_384;
const ENEMY_RADIUS: i64 = 1_024;

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct S1m4KernelCoverage {
    pub gate_work_cases: u64,
    pub junction_work_cases: u64,
    pub wire_work_cases: u64,
    pub substrate_work_cases: u64,
    pub redundant_vertex_checks: u64,
    pub strict_wire_growth_checks: u64,
    pub construction_progress_checks: u64,
    pub live_demand_cases: u64,
    pub live_final_ceil_cases: u64,
    pub contact_allocation_cases: u64,
    pub contact_remainder_cases: u64,
    pub contact_permutation_checks: u64,
    pub contact_conservation_checks: u64,
    pub heat_integration_cases: u64,
    pub damage_cases: u64,
    pub thermal_tie_checks: u64,
    pub order_rejection_checks: u64,
    pub numeric_boundary_checks: u64,
    pub command_tag8_checks: u64,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum S1m4KernelStage {
    Profile,
    ConstructionWork,
    ConstructionProgress,
    LiveDemand,
    ContactAllocation,
    HeatIntegration,
    Damage,
    Ordering,
    NumericBoundary,
    CommandEncoding,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum S1m4KernelInvariant {
    ProfileConstruction,
    WorkOracle,
    RedundantVertexIdentity,
    StrictWireGrowth,
    ProgressOracle,
    ProgressPermutation,
    LiveDemandOracle,
    ContactOracle,
    ContactPermutation,
    ContactConservation,
    HeatOracle,
    DamageOracle,
    ThermalTieToEven,
    TypedOrderingRejection,
    TypedNumericBoundary,
    CommandEncoderAgreement,
    CommandTag8,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum S1m4KernelExecutionObservation {
    KernelError {
        case_index: usize,
        stage: S1m4KernelStage,
    },
    InvariantViolation {
        case_index: usize,
        invariant: S1m4KernelInvariant,
    },
    Completed,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct S1m4KernelObservation {
    pub consumed_len: usize,
    pub generated_cases: usize,
    pub coverage: S1m4KernelCoverage,
    pub execution: S1m4KernelExecutionObservation,
}

impl S1m4KernelObservation {
    pub const fn invariant_failure(&self) -> Option<&'static str> {
        match self.execution {
            S1m4KernelExecutionObservation::KernelError { .. } => {
                Some("bounded S1-M4 input produced a public-kernel error")
            }
            S1m4KernelExecutionObservation::InvariantViolation { .. } => {
                Some("S1-M4 public-kernel output disagreed with an independent invariant")
            }
            S1m4KernelExecutionObservation::Completed => None,
        }
    }
}

/// Exercises bounded exact S1-M4 kernels against independent integer oracles.
pub fn exercise_s1m4_kernels(input: &[u8]) -> S1m4KernelObservation {
    let bounded = &input[..input.len().min(MAX_S1M4_KERNEL_INPUT_BYTES)];
    let mut observation = S1m4KernelObservation {
        consumed_len: bounded.len(),
        generated_cases: 0,
        coverage: S1m4KernelCoverage::default(),
        execution: S1m4KernelExecutionObservation::Completed,
    };
    let mut cursor = CyclicBytes::new(bounded);

    for (case_index, selector) in bounded.iter().copied().enumerate() {
        let mut balance = BalanceProfile::construction_contact_damage_alpha("s1m4-fuzz");
        let Some(construction) = balance.construction_probe.as_mut() else {
            return finish_kernel_invariant(
                observation,
                case_index,
                S1m4KernelInvariant::ProfileConstruction,
            );
        };
        let Some(contact) = balance.contact_damage_probe.as_mut() else {
            return finish_kernel_invariant(
                observation,
                case_index,
                S1m4KernelInvariant::ProfileConstruction,
            );
        };
        let Some(work_coefficient) = bounded_ratio(
            i64::from(1 + cursor.next_u8() % 7),
            i64::from(1 + cursor.next_u8() % 9),
        ) else {
            return finish_kernel_invariant(
                observation,
                case_index,
                S1m4KernelInvariant::ProfileConstruction,
            );
        };
        let Some(live_coefficient) = bounded_ratio(
            i64::from(1 + cursor.next_u8() % 7),
            i64::from(1 + cursor.next_u8() % 11),
        ) else {
            return finish_kernel_invariant(
                observation,
                case_index,
                S1m4KernelInvariant::ProfileConstruction,
            );
        };
        construction.wire_work_per_ncu = work_coefficient;
        construction.substrate_work_per_square_wu = work_coefficient;
        contact.live_energy_per_strength_wu = live_coefficient;

        if let Err(invariant) = exercise_work_case(
            selector,
            &mut cursor,
            construction,
            &mut observation.coverage,
        ) {
            return finish_kernel_invariant(observation, case_index, invariant);
        }
        if let Err(invariant) =
            exercise_progress_case(selector, &mut cursor, &mut observation.coverage)
        {
            return finish_kernel_invariant(observation, case_index, invariant);
        }
        if let Err(invariant) =
            exercise_live_demand_case(selector, &mut cursor, contact, &mut observation.coverage)
        {
            return finish_kernel_invariant(observation, case_index, invariant);
        }
        if let Err(invariant) =
            exercise_contact_case(selector, &mut cursor, &mut observation.coverage)
        {
            return finish_kernel_invariant(observation, case_index, invariant);
        }
        if let Err(invariant) = exercise_heat_case(selector, &mut cursor, &mut observation.coverage)
        {
            return finish_kernel_invariant(observation, case_index, invariant);
        }
        if let Err(invariant) =
            exercise_damage_case(selector, &mut cursor, contact, &mut observation.coverage)
        {
            return finish_kernel_invariant(observation, case_index, invariant);
        }

        observation.generated_cases += 1;
    }

    if let Err(invariant) = exercise_negative_boundaries(&mut observation.coverage) {
        return finish_kernel_invariant(observation, bounded.len(), invariant);
    }
    if let Err(invariant) = exercise_command_tag8(&mut observation.coverage) {
        return finish_kernel_invariant(observation, bounded.len(), invariant);
    }
    observation
}

fn exercise_work_case(
    selector: u8,
    cursor: &mut CyclicBytes<'_>,
    probe: &aon_sim::ConstructionProbeProfile,
    coverage: &mut S1m4KernelCoverage,
) -> Result<(), S1m4KernelInvariant> {
    let target = match selector % 4 {
        0 => {
            coverage.gate_work_cases += 1;
            let gate_type = match cursor.next_u8() % 3 {
                0 => GateType::And,
                1 => GateType::Or,
                _ => GateType::Not,
            };
            ConstructionTarget::Gate {
                gate_type,
                origin: point(0, 0),
                routing_domain: RoutingDomain::OpenWorld,
            }
        }
        1 => {
            coverage.junction_work_cases += 1;
            ConstructionTarget::Junction {
                routing_domain: RoutingDomain::OpenWorld,
                position: point(0, 0),
            }
        }
        2 => {
            coverage.wire_work_cases += 1;
            let whole = 1 + i64::from(cursor.next_u8() % 31);
            ConstructionTarget::Wire {
                routing_domain: RoutingDomain::OpenWorld,
                points: vec![point(0, 0), point(whole * WU, 0)],
                endpoint_a: EndpointTarget::Free,
                endpoint_b: EndpointTarget::Free,
            }
        }
        _ => {
            coverage.substrate_work_cases += 1;
            let width = 1 + i64::from(cursor.next_u8() % 15);
            let height = 1 + i64::from(cursor.next_u8() % 15);
            ConstructionTarget::FixedSubstrate {
                origin: point(0, 0),
                routing_area: FixedAabb::new(point(0, 0), point(width * WU, height * WU)),
                footprint: FixedAabb::new(point(0, 0), point(width * WU, height * WU)),
            }
        }
    };
    let observed =
        required_construction_work(&target, probe).map_err(|_| S1m4KernelInvariant::WorkOracle)?;
    let expected =
        independent_work_oracle(&target, probe).ok_or(S1m4KernelInvariant::WorkOracle)?;
    if observed != expected {
        return Err(S1m4KernelInvariant::WorkOracle);
    }

    let reference = BalanceProfile::construction_contact_damage_alpha("s1m4-growth")
        .construction_probe
        .ok_or(S1m4KernelInvariant::ProfileConstruction)?;
    let short = wire_target(&[point(0, 0), point(WU, 0)]);
    let redundant = wire_target(&[point(0, 0), point(WU / 2, 0), point(WU, 0)]);
    let long = wire_target(&[point(0, 0), point(2 * WU, 0)]);
    let short_work = required_construction_work(&short, &reference)
        .map_err(|_| S1m4KernelInvariant::RedundantVertexIdentity)?;
    if required_construction_work(&redundant, &reference) != Ok(short_work) {
        return Err(S1m4KernelInvariant::RedundantVertexIdentity);
    }
    coverage.redundant_vertex_checks += 1;
    let long_work = required_construction_work(&long, &reference)
        .map_err(|_| S1m4KernelInvariant::StrictWireGrowth)?;
    if long_work <= short_work {
        return Err(S1m4KernelInvariant::StrictWireGrowth);
    }
    coverage.strict_wire_growth_checks += 1;
    Ok(())
}

fn exercise_progress_case(
    selector: u8,
    cursor: &mut CyclicBytes<'_>,
    coverage: &mut S1m4KernelCoverage,
) -> Result<(), S1m4KernelInvariant> {
    let required = 2 + u64::from(selector % 31);
    let completed = u64::from(cursor.next_u8()) % required;
    let site_id = ConstructionSiteId(EntityId(100));
    let base = ConstructionSite {
        id: site_id,
        target: ConstructionTarget::Junction {
            routing_domain: RoutingDomain::OpenWorld,
            position: point(0, 0),
        },
        required_work: Energy(required),
        completed_work: Energy(completed),
        activation_ready: false,
    };
    let first = ConstructionWorkContribution {
        site: site_id,
        builder: MobileId(EntityId(5)),
        granted_work: Energy(1 + u64::from(cursor.next_u8() % 17)),
    };
    let second = ConstructionWorkContribution {
        site: site_id,
        builder: MobileId(EntityId(2)),
        granted_work: Energy(1 + u64::from(cursor.next_u8() % 17)),
    };
    let mut forward = ConstructionSiteStore::new(vec![base.clone()])
        .map_err(|_| S1m4KernelInvariant::ProgressOracle)?;
    let mut reverse =
        ConstructionSiteStore::new(vec![base]).map_err(|_| S1m4KernelInvariant::ProgressOracle)?;
    let forward_rows = apply_construction_work(&mut forward, &[first, second])
        .map_err(|_| S1m4KernelInvariant::ProgressOracle)?;
    let reverse_rows = apply_construction_work(&mut reverse, &[second, first])
        .map_err(|_| S1m4KernelInvariant::ProgressOracle)?;
    if forward != reverse || forward_rows != reverse_rows {
        return Err(S1m4KernelInvariant::ProgressPermutation);
    }
    let mut remaining = required - completed;
    let mut expected_completed = completed;
    for row in &forward_rows {
        let applied = row.granted_work.0.min(remaining);
        remaining -= applied;
        expected_completed += applied;
        if row.applied_work != Energy(applied)
            || row.completed_work != Energy(expected_completed)
            || row.activation_ready != (remaining == 0)
        {
            return Err(S1m4KernelInvariant::ProgressOracle);
        }
    }
    coverage.construction_progress_checks += 1;
    Ok(())
}

fn exercise_live_demand_case(
    selector: u8,
    cursor: &mut CyclicBytes<'_>,
    probe: &aon_sim::ContactDamageProbeProfile,
    coverage: &mut S1m4KernelCoverage,
) -> Result<(), S1m4KernelInvariant> {
    let length = i64::from(1 + selector % 31) * (WU / 4);
    let strength = u128::from(1 + cursor.next_u8() % 63);
    let input = aon_sim::LiveWireInput {
        wire: WireId(EntityId(9)),
        length: Fixed(length),
        high_drive_strength: strength,
    };
    let observed = calculate_live_wire_demand(input, probe)
        .map_err(|_| S1m4KernelInvariant::LiveDemandOracle)?;
    let numerator = u128::try_from(probe.live_energy_per_strength_wu.numerator())
        .ok()
        .and_then(|coefficient| coefficient.checked_mul(strength))
        .and_then(|value| value.checked_mul(length as u128))
        .ok_or(S1m4KernelInvariant::LiveDemandOracle)?;
    let denominator = u128::try_from(probe.live_energy_per_strength_wu.denominator())
        .ok()
        .and_then(|coefficient| coefficient.checked_mul(WU as u128))
        .ok_or(S1m4KernelInvariant::LiveDemandOracle)?;
    let expected = ceil_div(numerator, denominator)
        .and_then(|value| u64::try_from(value).ok())
        .map(Energy)
        .ok_or(S1m4KernelInvariant::LiveDemandOracle)?;
    if observed != expected {
        return Err(S1m4KernelInvariant::LiveDemandOracle);
    }
    coverage.live_demand_cases += 1;
    if !numerator.is_multiple_of(denominator) {
        coverage.live_final_ceil_cases += 1;
    }
    Ok(())
}

fn exercise_contact_case(
    selector: u8,
    cursor: &mut CyclicBytes<'_>,
    coverage: &mut S1m4KernelCoverage,
) -> Result<(), S1m4KernelInvariant> {
    let grant = Energy(u64::from(selector));
    let leak = 1 + u64::from(cursor.next_u8() % 17);
    let candidate_count = 1 + usize::from(cursor.next_u8() % 4);
    let mut candidates = (0..candidate_count)
        .map(|index| ContactCandidate {
            target: EnemyId(EntityId(2 + u64::try_from(index).unwrap_or(0) * 3)),
            weight: u128::from(1 + cursor.next_u8() % 13),
        })
        .collect::<Vec<_>>();
    let observed = allocate_contact_energy(grant, &candidates, leak)
        .map_err(|_| S1m4KernelInvariant::ContactOracle)?;
    let expected = independent_contact_oracle(grant, &candidates, leak)
        .ok_or(S1m4KernelInvariant::ContactOracle)?;
    if observed != expected {
        return Err(S1m4KernelInvariant::ContactOracle);
    }
    candidates.reverse();
    if allocate_contact_energy(grant, &candidates, leak) != Ok(observed.clone()) {
        return Err(S1m4KernelInvariant::ContactPermutation);
    }
    let conserved = observed
        .0
        .iter()
        .try_fold(observed.1.0, |sum, row| sum.checked_add(row.absorbed.0));
    if conserved != Some(grant.0) {
        return Err(S1m4KernelInvariant::ContactConservation);
    }
    coverage.contact_allocation_cases += 1;
    coverage.contact_permutation_checks += 1;
    coverage.contact_conservation_checks += 1;
    let total_weight = candidates.iter().map(|row| row.weight).sum::<u128>();
    let denominator = u128::from(leak) + total_weight;
    let budget = u128::from(grant.0) * total_weight / denominator;
    let bases = candidates
        .iter()
        .map(|row| u128::from(grant.0) * row.weight / denominator)
        .sum::<u128>();
    if budget > bases {
        coverage.contact_remainder_cases += 1;
    }
    Ok(())
}

fn exercise_heat_case(
    selector: u8,
    cursor: &mut CyclicBytes<'_>,
    coverage: &mut S1m4KernelCoverage,
) -> Result<(), S1m4KernelInvariant> {
    let current = HeatEnergy(u64::from(selector));
    let count = 1 + usize::from(cursor.next_u8() % 4);
    let rows = (0..count)
        .map(|index| HeatContributionInput {
            key: HeatContributionKey {
                kind: match index {
                    0 => InteractionHeatKind::GatePowerDissipation,
                    1 => InteractionHeatKind::Movement,
                    2 => InteractionHeatKind::Construction,
                    _ => InteractionHeatKind::LiveWireRemainder,
                },
                source: EntityId(10 + u64::try_from(index).unwrap_or(0)),
                demand: None,
            },
            energy: HeatEnergy(1 + u64::from(cursor.next_u8() % 31)),
        })
        .collect::<Vec<_>>();
    let expected = rows
        .iter()
        .try_fold(current.0, |sum, row| sum.checked_add(row.energy.0))
        .map(HeatEnergy)
        .ok_or(S1m4KernelInvariant::HeatOracle)?;
    if integrate_heat(EntityId(1), current, &rows) != Ok(expected) {
        return Err(S1m4KernelInvariant::HeatOracle);
    }
    coverage.heat_integration_cases += 1;
    Ok(())
}

fn exercise_damage_case(
    selector: u8,
    cursor: &mut CyclicBytes<'_>,
    probe: &mut aon_sim::ContactDamageProbeProfile,
    coverage: &mut S1m4KernelCoverage,
) -> Result<(), S1m4KernelInvariant> {
    probe.electrical_tolerance.wire = 1 + u64::from(cursor.next_u8() % 13);
    probe.thermal_capacity.wire = 1 + u64::from(cursor.next_u8() % 13);
    probe.safe_temperature = Fixed(i64::from(cursor.next_u8() % 4) * WU);
    probe.thermal_damage_rate = bounded_ratio(
        i64::from(1 + cursor.next_u8() % 5),
        i64::from(1 + cursor.next_u8() % 7),
    )
    .ok_or(S1m4KernelInvariant::ProfileConstruction)?;
    let target = EntityId(50);
    let integrity = 1 + u64::from(cursor.next_u8() % 100);
    let temperature = i64::from(selector % 12) * (WU / 2);
    let count = 1 + usize::from(cursor.next_u8() % 4);
    let exposures = (0..count)
        .map(|index| ElectricalExposure {
            target,
            source: EntityId(2 + u64::try_from(index).unwrap_or(0)),
            energy: Energy(u64::from(cursor.next_u8() % 31)),
        })
        .collect::<Vec<_>>();
    let snapshot = DamageSnapshot {
        target,
        kind: ThermalObjectKind::Wire,
        integrity: Integrity(integrity),
        phase1_temperature: Fixed(temperature),
    };
    let observed = resolve_damage(snapshot, &exposures, probe)
        .map_err(|_| S1m4KernelInvariant::DamageOracle)?;
    let exposure = exposures.iter().map(|row| row.energy.0).sum::<u64>();
    let electrical = exposure / probe.electrical_tolerance.wire;
    let excess = temperature.saturating_sub(probe.safe_temperature.0).max(0) as u128;
    let thermal_n = u128::try_from(probe.thermal_damage_rate.numerator())
        .ok()
        .and_then(|value| value.checked_mul(excess))
        .ok_or(S1m4KernelInvariant::DamageOracle)?;
    let thermal_d = u128::try_from(probe.thermal_damage_rate.denominator())
        .ok()
        .and_then(|value| value.checked_mul(WU as u128))
        .ok_or(S1m4KernelInvariant::DamageOracle)?;
    let thermal = nearest_ties_even(thermal_n, thermal_d)
        .and_then(|value| u64::try_from(value).ok())
        .ok_or(S1m4KernelInvariant::DamageOracle)?;
    let total = electrical
        .checked_add(thermal)
        .ok_or(S1m4KernelInvariant::DamageOracle)?;
    let after = integrity.saturating_sub(total);
    if observed.electrical_exposure != Energy(exposure)
        || observed.electrical_damage != Integrity(electrical)
        || observed.thermal_damage != Integrity(thermal)
        || observed.integrity_after != Integrity(after)
        || observed.pending_destruction != (integrity > 0 && after == 0)
    {
        return Err(S1m4KernelInvariant::DamageOracle);
    }
    coverage.damage_cases += 1;

    let mut tie_probe = *probe;
    tie_probe.safe_temperature = Fixed::ZERO;
    tie_probe.thermal_damage_rate =
        Rational::new(1, 1).map_err(|_| S1m4KernelInvariant::ThermalTieToEven)?;
    let even = resolve_damage(
        DamageSnapshot {
            phase1_temperature: Fixed(WU / 2),
            integrity: Integrity(10),
            ..snapshot
        },
        &[],
        &tie_probe,
    )
    .map_err(|_| S1m4KernelInvariant::ThermalTieToEven)?;
    let odd = resolve_damage(
        DamageSnapshot {
            phase1_temperature: Fixed(WU + WU / 2),
            integrity: Integrity(10),
            ..snapshot
        },
        &[],
        &tie_probe,
    )
    .map_err(|_| S1m4KernelInvariant::ThermalTieToEven)?;
    if (even.thermal_damage, odd.thermal_damage) != (Integrity(0), Integrity(2)) {
        return Err(S1m4KernelInvariant::ThermalTieToEven);
    }
    coverage.thermal_tie_checks += 1;
    Ok(())
}

fn exercise_negative_boundaries(
    coverage: &mut S1m4KernelCoverage,
) -> Result<(), S1m4KernelInvariant> {
    let owner = EntityId(77);
    let low = HeatContributionInput {
        key: HeatContributionKey {
            kind: InteractionHeatKind::Movement,
            source: EntityId(2),
            demand: None,
        },
        energy: HeatEnergy(1),
    };
    let high = HeatContributionInput {
        key: HeatContributionKey {
            kind: InteractionHeatKind::Construction,
            source: EntityId(3),
            demand: None,
        },
        energy: HeatEnergy(1),
    };
    if integrate_heat(owner, HeatEnergy(0), &[high, low])
        != Err(ThermalDamageError::NonCanonicalHeatOrder { owner })
        || integrate_heat(owner, HeatEnergy(0), &[low, low])
            != Err(ThermalDamageError::DuplicateHeatContribution { owner })
    {
        return Err(S1m4KernelInvariant::TypedOrderingRejection);
    }

    let probe = BalanceProfile::construction_contact_damage_alpha("s1m4-boundaries")
        .contact_damage_probe
        .ok_or(S1m4KernelInvariant::ProfileConstruction)?;
    let target = EntityId(99);
    let snapshot = DamageSnapshot {
        target,
        kind: ThermalObjectKind::Wire,
        integrity: Integrity(10),
        phase1_temperature: Fixed::ZERO,
    };
    let earlier = ElectricalExposure {
        target,
        source: EntityId(2),
        energy: Energy(1),
    };
    let later = ElectricalExposure {
        target,
        source: EntityId(3),
        energy: Energy(1),
    };
    if resolve_damage(snapshot, &[later, earlier], &probe)
        != Err(ThermalDamageError::NonCanonicalExposureOrder)
        || !matches!(
            resolve_damage(snapshot, &[earlier, earlier], &probe),
            Err(ThermalDamageError::DuplicateExposureSource { .. })
        )
    {
        return Err(S1m4KernelInvariant::TypedOrderingRejection);
    }
    coverage.order_rejection_checks += 4;

    if integrate_heat(owner, HeatEnergy(u64::MAX), &[low])
        != Err(ThermalDamageError::ArithmeticOverflow)
    {
        return Err(S1m4KernelInvariant::TypedNumericBoundary);
    }
    let duplicate = ContactCandidate {
        target: EnemyId(EntityId(4)),
        weight: 1,
    };
    if !matches!(
        allocate_contact_energy(Energy(1), &[duplicate, duplicate], 1),
        Err(aon_sim::ContactError::DuplicateTarget { .. })
    ) || !matches!(
        allocate_contact_energy(
            Energy(u64::MAX),
            &[
                ContactCandidate {
                    target: EnemyId(EntityId(4)),
                    weight: u128::MAX,
                },
                ContactCandidate {
                    target: EnemyId(EntityId(5)),
                    weight: 1,
                },
            ],
            1,
        ),
        Err(aon_sim::ContactError::ArithmeticOverflow)
    ) {
        return Err(S1m4KernelInvariant::TypedNumericBoundary);
    }
    let mut invalid_probe = probe;
    invalid_probe.electrical_tolerance.wire = 0;
    if resolve_damage(snapshot, &[], &invalid_probe)
        != Err(ThermalDamageError::NonPositiveElectricalTolerance(
            ThermalObjectKind::Wire,
        ))
    {
        return Err(S1m4KernelInvariant::TypedNumericBoundary);
    }
    coverage.numeric_boundary_checks += 4;
    Ok(())
}

fn exercise_command_tag8(coverage: &mut S1m4KernelCoverage) -> Result<(), S1m4KernelInvariant> {
    let targets = [
        ConstructionTarget::Gate {
            gate_type: GateType::And,
            origin: point(0, 0),
            routing_domain: RoutingDomain::OpenWorld,
        },
        wire_target(&[point(0, 0), point(WU, 0)]),
        ConstructionTarget::Junction {
            routing_domain: RoutingDomain::OpenWorld,
            position: point(0, 0),
        },
        ConstructionTarget::FixedSubstrate {
            origin: point(0, 0),
            routing_area: FixedAabb::new(point(0, 0), point(WU, WU)),
            footprint: FixedAabb::new(point(0, 0), point(WU, WU)),
        },
    ];
    for (target_tag, target) in targets.into_iter().enumerate() {
        let envelope = CommandEnvelope {
            target_tick: Tick(7),
            ordinal: 11,
            command: Command::PlaceConstructionSite(PlaceConstructionSiteCommand { target }),
        };
        let allocated = envelope
            .canonical_bytes()
            .map_err(|_| S1m4KernelInvariant::CommandEncoderAgreement)?;
        let mut streamed = Vec::new();
        envelope
            .write_canonical(&mut |bytes| streamed.extend_from_slice(bytes))
            .map_err(|_| S1m4KernelInvariant::CommandEncoderAgreement)?;
        if allocated != streamed {
            return Err(S1m4KernelInvariant::CommandEncoderAgreement);
        }
        // Domain (15), encoder version (2), Tick (8), ordinal (8), then Command tag.
        if allocated.get(33) != Some(&8)
            || allocated.get(34) != u8::try_from(target_tag).ok().as_ref()
        {
            return Err(S1m4KernelInvariant::CommandTag8);
        }
        coverage.command_tag8_checks += 1;
    }
    Ok(())
}

fn independent_work_oracle(
    target: &ConstructionTarget,
    probe: &aon_sim::ConstructionProbeProfile,
) -> Option<Energy> {
    let value = match target {
        ConstructionTarget::Gate { gate_type, .. } => u128::from(match gate_type {
            GateType::And => probe.and_gate_work,
            GateType::Or => probe.or_gate_work,
            GateType::Not => probe.not_gate_work,
        }),
        ConstructionTarget::Junction { .. } => u128::from(probe.junction_base_work),
        ConstructionTarget::Wire { points, .. } => {
            let length = independent_axis_length(points)?;
            u128::from(probe.wire_endpoint_work).checked_add(rational_ceil(
                probe.wire_work_per_ncu,
                &[length],
                &[WU as u128],
            )?)?
        }
        ConstructionTarget::FixedSubstrate { footprint, .. } => {
            let width =
                u128::try_from(i128::from(footprint.max.x.0) - i128::from(footprint.min.x.0))
                    .ok()?;
            let height =
                u128::try_from(i128::from(footprint.max.y.0) - i128::from(footprint.min.y.0))
                    .ok()?;
            rational_ceil(
                probe.substrate_work_per_square_wu,
                &[width, height],
                &[WU as u128, WU as u128],
            )?
        }
    };
    u64::try_from(value).ok().map(Energy)
}

fn independent_axis_length(points: &[FixedVec2]) -> Option<u128> {
    if points.len() < 2 {
        return None;
    }
    points.windows(2).try_fold(0_u128, |sum, pair| {
        let dx = (i128::from(pair[1].x.0) - i128::from(pair[0].x.0)).unsigned_abs();
        let dy = (i128::from(pair[1].y.0) - i128::from(pair[0].y.0)).unsigned_abs();
        if dx != 0 && dy != 0 {
            return None;
        }
        sum.checked_add(dx + dy)
    })
}

fn rational_ceil(coefficient: Rational, factors: &[u128], divisors: &[u128]) -> Option<u128> {
    let numerator = factors.iter().try_fold(
        u128::try_from(coefficient.numerator()).ok()?,
        |value, factor| value.checked_mul(*factor),
    )?;
    let denominator = divisors.iter().try_fold(
        u128::try_from(coefficient.denominator()).ok()?,
        |value, factor| value.checked_mul(*factor),
    )?;
    ceil_div(numerator, denominator)
}

fn independent_contact_oracle(
    grant: Energy,
    candidates: &[ContactCandidate],
    leak: u64,
) -> Option<(Vec<ContactAllocation>, HeatEnergy)> {
    let mut candidates = candidates.to_vec();
    candidates.sort_unstable_by_key(|candidate| candidate.target);
    if grant.0 == 0 {
        return Some((Vec::new(), HeatEnergy(0)));
    }
    let total_weight = candidates
        .iter()
        .try_fold(0_u128, |sum, row| sum.checked_add(row.weight))?;
    let denominator = u128::from(leak).checked_add(total_weight)?;
    let target_budget = u128::from(grant.0).checked_mul(total_weight)? / denominator;
    let mut base_sum = 0_u128;
    let mut rows = candidates
        .into_iter()
        .map(|candidate| {
            let absorbed = u128::from(grant.0).checked_mul(candidate.weight)? / denominator;
            base_sum = base_sum.checked_add(absorbed)?;
            Some(ContactAllocation {
                target: candidate.target,
                weight: candidate.weight,
                absorbed: Energy(u64::try_from(absorbed).ok()?),
            })
        })
        .collect::<Option<Vec<_>>>()?;
    let remainder = usize::try_from(target_budget.checked_sub(base_sum)?).ok()?;
    for row in rows.iter_mut().take(remainder) {
        row.absorbed = row.absorbed.checked_add(Energy(1)).ok()?;
    }
    let absorbed = rows
        .iter()
        .try_fold(0_u64, |sum, row| sum.checked_add(row.absorbed.0))?;
    Some((rows, HeatEnergy(grant.0.checked_sub(absorbed)?)))
}

const fn ceil_div(numerator: u128, denominator: u128) -> Option<u128> {
    if denominator == 0 {
        return None;
    }
    let quotient = numerator / denominator;
    if numerator.is_multiple_of(denominator) {
        Some(quotient)
    } else {
        quotient.checked_add(1)
    }
}

fn nearest_ties_even(numerator: u128, denominator: u128) -> Option<u128> {
    if denominator == 0 {
        return None;
    }
    let quotient = numerator / denominator;
    let remainder = numerator % denominator;
    let doubled = remainder.checked_mul(2)?;
    if doubled < denominator || (doubled == denominator && quotient.is_multiple_of(2)) {
        Some(quotient)
    } else {
        quotient.checked_add(1)
    }
}

fn wire_target(points: &[FixedVec2]) -> ConstructionTarget {
    ConstructionTarget::Wire {
        routing_domain: RoutingDomain::OpenWorld,
        points: points.to_vec(),
        endpoint_a: EndpointTarget::Free,
        endpoint_b: EndpointTarget::Free,
    }
}

fn bounded_ratio(numerator: i64, denominator: i64) -> Option<Rational> {
    Rational::new(numerator, denominator).ok()
}

fn finish_kernel_invariant(
    mut observation: S1m4KernelObservation,
    case_index: usize,
    invariant: S1m4KernelInvariant,
) -> S1m4KernelObservation {
    observation.execution = S1m4KernelExecutionObservation::InvariantViolation {
        case_index,
        invariant,
    };
    observation
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum S1m4RuntimeScenario {
    ConstructionActivation,
    C09WireBreak,
    MainCoreRunEnd,
    MutualLethalCompletion,
    HostileFrameSensingOnly,
    TwoTickThermalDamage,
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct S1m4RuntimeCoverage {
    pub construction_progress: u64,
    pub construction_next_phase0_activation: u64,
    pub construction_fresh_identity: u64,
    pub c09_pending_wire_current_tick: u64,
    pub c09_next_phase0_removal: u64,
    pub c09_stale_arrival: u64,
    pub terminal_tick_commits: u64,
    pub terminal_later_step_rejections: u64,
    pub terminal_read_only_checks: u64,
    pub mutual_lethal_current_tick_completions: u64,
    pub mutual_lethal_next_phase0_removals: u64,
    pub hostile_frame_sensing_only_checks: u64,
    pub thermal_heat_tick_checks: u64,
    pub thermal_next_tick_damage_checks: u64,
    pub reproducibility_checks: u64,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum S1m4RuntimeStage {
    Profile,
    Simulation,
    PrefixStep,
    CommandAcceptance,
    ConstructionProgress,
    ConstructionActivation,
    C09Pending,
    C09Removal,
    C09StaleArrival,
    TerminalCommit,
    TerminalReadOnly,
    MutualLethalTick,
    MutualLethalRemoval,
    HostileFrameSensingOnly,
    ThermalHeatLoad,
    ThermalHeatReport,
    ThermalHeatState,
    ThermalNextTickDamage,
    Reproducibility,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum S1m4RuntimeExecutionObservation {
    Failure {
        case_index: usize,
        scenario: S1m4RuntimeScenario,
        stage: S1m4RuntimeStage,
    },
    Completed,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct S1m4RuntimeObservation {
    pub consumed_len: usize,
    pub generated_scenarios: usize,
    pub generated_steps: usize,
    pub state_hashes: Vec<StateHash>,
    pub coverage: S1m4RuntimeCoverage,
    pub execution: S1m4RuntimeExecutionObservation,
}

impl S1m4RuntimeObservation {
    pub const fn invariant_failure(&self) -> Option<&'static str> {
        match self.execution {
            S1m4RuntimeExecutionObservation::Failure { .. } => {
                Some("bounded S1-M4 stateful runtime scenario violated its exact contract")
            }
            S1m4RuntimeExecutionObservation::Completed => None,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
struct RuntimeTrace {
    state_hashes: Vec<StateHash>,
    steps: usize,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
struct RuntimeFailure {
    stage: S1m4RuntimeStage,
}

impl RuntimeFailure {
    const fn at(stage: S1m4RuntimeStage) -> Self {
        Self { stage }
    }
}

/// Replays bounded public `Simulation` micro-scenarios for the stateful S1-M4 boundaries.
///
/// Each selected scenario is executed twice from a fresh package. Full exact assertions happen
/// inside the scenario and both State-hash traces must agree before the observation is accepted.
pub fn exercise_s1m4_runtime(input: &[u8]) -> S1m4RuntimeObservation {
    let bounded = &input[..input.len().min(MAX_S1M4_RUNTIME_INPUT_BYTES)];
    let mut observation = S1m4RuntimeObservation {
        consumed_len: bounded.len(),
        generated_scenarios: 0,
        generated_steps: 0,
        state_hashes: Vec::new(),
        coverage: S1m4RuntimeCoverage::default(),
        execution: S1m4RuntimeExecutionObservation::Completed,
    };

    for (case_index, selector) in bounded.iter().copied().enumerate() {
        let scenario = match selector % 6 {
            0 => S1m4RuntimeScenario::ConstructionActivation,
            1 => S1m4RuntimeScenario::C09WireBreak,
            2 => S1m4RuntimeScenario::MainCoreRunEnd,
            3 => S1m4RuntimeScenario::MutualLethalCompletion,
            4 => S1m4RuntimeScenario::HostileFrameSensingOnly,
            _ => S1m4RuntimeScenario::TwoTickThermalDamage,
        };
        let run = || match scenario {
            S1m4RuntimeScenario::ConstructionActivation => run_construction_runtime(),
            S1m4RuntimeScenario::C09WireBreak => run_c09_runtime(),
            S1m4RuntimeScenario::MainCoreRunEnd => run_terminal_runtime(),
            S1m4RuntimeScenario::MutualLethalCompletion => run_mutual_lethal_runtime(),
            S1m4RuntimeScenario::HostileFrameSensingOnly => run_hostile_frame_runtime(),
            S1m4RuntimeScenario::TwoTickThermalDamage => run_two_tick_thermal_runtime(),
        };
        let first = match run() {
            Ok(trace) => trace,
            Err(failure) => {
                return finish_runtime_failure(observation, case_index, scenario, failure.stage);
            }
        };
        let second = match run() {
            Ok(trace) => trace,
            Err(failure) => {
                return finish_runtime_failure(observation, case_index, scenario, failure.stage);
            }
        };
        if first != second {
            return finish_runtime_failure(
                observation,
                case_index,
                scenario,
                S1m4RuntimeStage::Reproducibility,
            );
        }
        observation.generated_scenarios += 1;
        observation.generated_steps += first.steps;
        observation.state_hashes.extend(first.state_hashes);
        observation.coverage.reproducibility_checks += 1;
        match scenario {
            S1m4RuntimeScenario::ConstructionActivation => {
                observation.coverage.construction_progress += 1;
                observation.coverage.construction_next_phase0_activation += 1;
                observation.coverage.construction_fresh_identity += 1;
            }
            S1m4RuntimeScenario::C09WireBreak => {
                observation.coverage.c09_pending_wire_current_tick += 1;
                observation.coverage.c09_next_phase0_removal += 1;
                observation.coverage.c09_stale_arrival += 1;
            }
            S1m4RuntimeScenario::MainCoreRunEnd => {
                observation.coverage.terminal_tick_commits += 1;
                observation.coverage.terminal_later_step_rejections += 1;
                observation.coverage.terminal_read_only_checks += 1;
            }
            S1m4RuntimeScenario::MutualLethalCompletion => {
                observation.coverage.mutual_lethal_current_tick_completions += 1;
                observation.coverage.mutual_lethal_next_phase0_removals += 1;
            }
            S1m4RuntimeScenario::HostileFrameSensingOnly => {
                observation.coverage.hostile_frame_sensing_only_checks += 1;
            }
            S1m4RuntimeScenario::TwoTickThermalDamage => {
                observation.coverage.thermal_heat_tick_checks += 1;
                observation.coverage.thermal_next_tick_damage_checks += 1;
            }
        }
    }
    observation
}

fn finish_runtime_failure(
    mut observation: S1m4RuntimeObservation,
    case_index: usize,
    scenario: S1m4RuntimeScenario,
    stage: S1m4RuntimeStage,
) -> S1m4RuntimeObservation {
    observation.execution = S1m4RuntimeExecutionObservation::Failure {
        case_index,
        scenario,
        stage,
    };
    observation
}

fn run_construction_runtime() -> Result<RuntimeTrace, RuntimeFailure> {
    let mut simulation = Simulation::new(s1m4_package(
        "s1m4-fuzz-construction",
        Some((wu(-2, 0), 500)),
        vec![enemy(wu(100, 100))],
        |_| {},
    )?)
    .map_err(|_| RuntimeFailure::at(S1m4RuntimeStage::Simulation))?;
    let source = simulation
        .power_sources()
        .next()
        .map(|state| state.id())
        .ok_or(RuntimeFailure::at(S1m4RuntimeStage::Simulation))?;
    let mut trace = RuntimeTrace {
        state_hashes: Vec::new(),
        steps: 0,
    };
    let track = step_commands(
        &mut simulation,
        vec![Command::PlaceWire(PlaceWireCommand {
            routing_domain: RoutingDomain::OpenWorld,
            points: vec![wu(-2, 0), wu(6, 0)],
            endpoint_a: EndpointTarget::PowerSourceAnchor(source),
            endpoint_b: EndpointTarget::Free,
        })],
    )?;
    record_step(&mut trace, &track);
    let base = step_commands(
        &mut simulation,
        vec![Command::PlaceFixedSubstrate(PlaceFixedSubstrateCommand {
            origin: point(0, 0),
            routing_area: large_bounds(),
            footprint: large_bounds(),
        })],
    )?;
    record_step(&mut trace, &base);
    let base_id = created_entity(&base, 0)?;
    let mobile = step_commands(
        &mut simulation,
        vec![Command::PlaceMobileSubstrate(PlaceMobileSubstrateCommand {
            origin: point(0, 0),
            routing_area: mobile_bounds(),
            footprint: mobile_bounds(),
        })],
    )?;
    record_step(&mut trace, &mobile);
    let mobile_id = MobileId(created_entity(&mobile, 0)?);
    let target = ConstructionTarget::Junction {
        routing_domain: RoutingDomain::FixedSubstrate(base_id),
        position: wu(0, 1),
    };
    let completed = step_commands(
        &mut simulation,
        vec![
            Command::PlaceConstructionSite(PlaceConstructionSiteCommand { target }),
            Command::SetExternalDriver(SetExternalDriverCommand {
                // The Track Wire owns Sense Drivers 1/2; the v5 Mobile appends BUILD as 3.
                driver: DriverId(EntityId(3)),
                level: LogicLevel::High,
                strength: DriveStrength(400),
            }),
        ],
    )?;
    record_step(&mut trace, &completed);
    let site = ConstructionSiteId(created_entity(&completed, 0)?);
    let work = completed
        .construction_work
        .first()
        .ok_or(RuntimeFailure::at(S1m4RuntimeStage::ConstructionProgress))?;
    if completed.construction_work.len() != 1
        || (work.site, work.builder) != (site, mobile_id)
        || work.granted_work != work.requested
        || work.applied_work != work.requested
        || simulation
            .construction_sites()
            .get(site)
            .is_none_or(|state| !state.activation_ready)
    {
        return Err(RuntimeFailure::at(S1m4RuntimeStage::ConstructionProgress));
    }
    let activated = step_commands(&mut simulation, vec![])?;
    record_step(&mut trace, &activated);
    let mut snapshot = aon_sim::RenderSnapshot::default();
    simulation.write_render_snapshot(&mut snapshot);
    let active = snapshot
        .junctions()
        .iter()
        .map(|row| row.id.entity_id())
        .find(|id| *id > site.entity_id());
    if simulation.construction_sites().get(site).is_some() || active.is_none() {
        return Err(RuntimeFailure::at(S1m4RuntimeStage::ConstructionActivation));
    }
    Ok(trace)
}

fn run_c09_runtime() -> Result<RuntimeTrace, RuntimeFailure> {
    let mut simulation = Simulation::new(s1m4_package(
        "s1m4-fuzz-c09",
        Some((wu(-1, 5), 100)),
        vec![enemy(wu(10, 0))],
        |_| {},
    )?)
    .map_err(|_| RuntimeFailure::at(S1m4RuntimeStage::Simulation))?;
    let source = simulation
        .power_sources()
        .next()
        .map(|state| state.id())
        .ok_or(RuntimeFailure::at(S1m4RuntimeStage::Simulation))?;
    let mut trace = RuntimeTrace {
        state_hashes: Vec::new(),
        steps: 0,
    };
    let substrate = step_commands(
        &mut simulation,
        vec![Command::PlaceFixedSubstrate(PlaceFixedSubstrateCommand {
            origin: point(0, 0),
            routing_area: large_bounds(),
            footprint: large_bounds(),
        })],
    )?;
    record_step(&mut trace, &substrate);
    let substrate = created_entity(&substrate, 0)?;
    let source_gate = step_commands(
        &mut simulation,
        vec![Command::PlaceGate(PlaceGateCommand {
            gate_type: GateType::Not,
            origin: point(0, 0),
            routing_domain: RoutingDomain::FixedSubstrate(substrate),
        })],
    )?;
    record_step(&mut trace, &source_gate);
    let source_gate = GateId(created_entity(&source_gate, 0)?);
    let power = step_commands(
        &mut simulation,
        vec![Command::PlaceWire(PlaceWireCommand {
            routing_domain: RoutingDomain::FixedSubstrate(substrate),
            points: vec![wu(-1, 5), wu(-1, -1), wu(0, -1), point(0, -CIRCUIT_PITCH)],
            endpoint_a: EndpointTarget::PowerSourceAnchor(source),
            endpoint_b: gate_power(source_gate),
        })],
    )?;
    record_step(&mut trace, &power);
    let mut settled = false;
    for _ in 0..16 {
        if simulation
            .gate_signal_state(source_gate)
            .is_some_and(|state| state.current_output == LogicLevel::High)
        {
            settled = true;
            break;
        }
        let report = step_commands(&mut simulation, vec![])?;
        record_step(&mut trace, &report);
    }
    if !settled {
        return Err(RuntimeFailure::at(S1m4RuntimeStage::PrefixStep));
    }
    let downstream = step_commands(
        &mut simulation,
        vec![Command::PlaceGate(PlaceGateCommand {
            gate_type: GateType::Not,
            origin: point(20 * WU + 2 * CIRCUIT_PITCH, 0),
            routing_domain: RoutingDomain::FixedSubstrate(substrate),
        })],
    )?;
    record_step(&mut trace, &downstream);
    let downstream = GateId(created_entity(&downstream, 0)?);
    let attacked = step_commands(
        &mut simulation,
        vec![Command::PlaceWire(PlaceWireCommand {
            routing_domain: RoutingDomain::FixedSubstrate(substrate),
            points: vec![point(CIRCUIT_PITCH, 0), point(20 * WU + CIRCUIT_PITCH, 0)],
            endpoint_a: gate_output(source_gate),
            endpoint_b: gate_input(downstream),
        })],
    )?;
    record_step(&mut trace, &attacked);
    let victim = WireId(created_entity(&attacked, 0)?);
    let damage = attacked
        .damage
        .iter()
        .find(|row| row.target == victim.entity_id());
    if attacked.signal_counters.topology_sync_arrivals_staged != 1
        || damage.is_none_or(|row| {
            row.electrical_exposure != Energy(10)
                || row.integrity_after != Integrity(0)
                || !row.pending_destruction
        })
        || simulation.wire_signal_state(victim).is_none()
        || simulation.wire_sense_state(victim).is_none()
    {
        return Err(RuntimeFailure::at(S1m4RuntimeStage::C09Pending));
    }
    let removed = step_commands(&mut simulation, vec![])?;
    record_step(&mut trace, &removed);
    if removed.destructions.len() != 1
        || removed.destructions[0].target != victim.entity_id()
        || simulation.wire_signal_state(victim).is_some()
        || simulation.wire_sense_state(victim).is_some()
    {
        return Err(RuntimeFailure::at(S1m4RuntimeStage::C09Removal));
    }
    let mut stale = false;
    for _ in 0..32 {
        let report = step_commands(&mut simulation, vec![])?;
        record_step(&mut trace, &report);
        if report.signal_counters.invalid_path_arrivals > 0 {
            stale = report.signal_counters.invalid_path_arrivals == 1
                && report.signal_counters.signal_arrivals_applied == 0;
            break;
        }
    }
    if !stale {
        return Err(RuntimeFailure::at(S1m4RuntimeStage::C09StaleArrival));
    }
    Ok(trace)
}

fn run_terminal_runtime() -> Result<RuntimeTrace, RuntimeFailure> {
    let mut simulation = Simulation::new(s1m4_package(
        "s1m4-fuzz-terminal",
        None,
        vec![enemy(wu(-100, -100))],
        |balance| {
            if let Some(probe) = balance.contact_damage_probe.as_mut() {
                probe.enemy_attack_energy_per_tick = 100;
            }
        },
    )?)
    .map_err(|_| RuntimeFailure::at(S1m4RuntimeStage::Simulation))?;
    let initial = simulation.state_hash();
    let terminal = simulation
        .step(&[])
        .map_err(|_| RuntimeFailure::at(S1m4RuntimeStage::TerminalCommit))?;
    let expected = RunStatus::Ended {
        completed_tick: Tick(0),
        cause: RunEndCause::MainCoreDestroyed,
    };
    if terminal.run_status != expected
        || terminal.state_hash != simulation.state_hash()
        || terminal.state_hash == initial
    {
        return Err(RuntimeFailure::at(S1m4RuntimeStage::TerminalCommit));
    }
    let terminal_hash = simulation.state_hash();
    let next_tick = simulation.next_tick();
    if simulation.step(&[]) != Err(SimulationError::RunEnded)
        || simulation.state_hash() != terminal_hash
        || simulation.next_tick() != next_tick
        || simulation.run_status() != expected
    {
        return Err(RuntimeFailure::at(S1m4RuntimeStage::TerminalReadOnly));
    }
    Ok(RuntimeTrace {
        state_hashes: vec![terminal_hash],
        steps: 1,
    })
}

fn run_mutual_lethal_runtime() -> Result<RuntimeTrace, RuntimeFailure> {
    let mut simulation = Simulation::new(s1m4_package(
        "s1m4-fuzz-mutual-lethal",
        Some((wu(-1, 5), 500)),
        vec![enemy(wu(1, 5))],
        |balance| {
            if let Some(probe) = balance.contact_damage_probe.as_mut() {
                probe.live_energy_per_strength_wu =
                    Rational::new(1, 260).expect("bounded exact coefficient");
                probe.world_leak_weight = 2;
            }
        },
    )?)
    .map_err(|_| RuntimeFailure::at(S1m4RuntimeStage::Simulation))?;
    let source = simulation
        .power_sources()
        .next()
        .map(|state| state.id())
        .ok_or(RuntimeFailure::at(S1m4RuntimeStage::Simulation))?;
    let enemy_id = simulation
        .enemies()
        .iter()
        .next()
        .map(|state| state.id())
        .ok_or(RuntimeFailure::at(S1m4RuntimeStage::Simulation))?;
    let mut trace = RuntimeTrace {
        state_hashes: Vec::new(),
        steps: 0,
    };

    let substrate = step_commands(
        &mut simulation,
        vec![Command::PlaceFixedSubstrate(PlaceFixedSubstrateCommand {
            origin: point(0, 0),
            routing_area: large_bounds(),
            footprint: large_bounds(),
        })],
    )?;
    record_step(&mut trace, &substrate);
    let substrate = created_entity(&substrate, 0)?;
    let gate = step_commands(
        &mut simulation,
        vec![Command::PlaceGate(PlaceGateCommand {
            gate_type: GateType::Not,
            origin: point(0, 0),
            routing_domain: RoutingDomain::FixedSubstrate(substrate),
        })],
    )?;
    record_step(&mut trace, &gate);
    let gate = GateId(created_entity(&gate, 0)?);
    let power = step_commands(
        &mut simulation,
        vec![Command::PlaceWire(PlaceWireCommand {
            routing_domain: RoutingDomain::FixedSubstrate(substrate),
            points: vec![wu(-1, 5), wu(-1, -1), wu(0, -1), point(0, -CIRCUIT_PITCH)],
            endpoint_a: EndpointTarget::PowerSourceAnchor(source),
            endpoint_b: gate_power(gate),
        })],
    )?;
    record_step(&mut trace, &power);
    let mut settled = false;
    for _ in 0..16 {
        if simulation
            .gate_signal_state(gate)
            .is_some_and(|state| state.current_output == LogicLevel::High)
        {
            settled = true;
            break;
        }
        let report = step_commands(&mut simulation, vec![])?;
        record_step(&mut trace, &report);
    }
    if !settled {
        return Err(RuntimeFailure::at(S1m4RuntimeStage::PrefixStep));
    }

    let attacked = step_commands(
        &mut simulation,
        vec![mutual_live_wire_command(substrate, gate, source)],
    )?;
    record_step(&mut trace, &attacked);
    let wire = WireId(created_entity(&attacked, 0)?);
    let live = attacked
        .power
        .as_ref()
        .and_then(|power| power.load(DemandId::new(wire.entity_id(), DemandKind::LiveWire)));
    let contact = attacked.contacts.first();
    let enemy_damage = attacked
        .damage
        .iter()
        .find(|row| row.target == enemy_id.entity_id());
    let wire_damage = attacked
        .damage
        .iter()
        .find(|row| row.target == wire.entity_id());
    if live.is_none_or(|row| (row.nominal, row.granted) != (Energy(30), Energy(30)))
        || attacked.contacts.len() != 1
        || contact.is_none_or(|row| {
            row.wire != wire || row.target != enemy_id || row.absorbed != Energy(10)
        })
        || enemy_damage.is_none_or(|row| {
            row.electrical_exposure != Energy(10)
                || row.integrity_after != Integrity(0)
                || !row.pending_destruction
        })
        || wire_damage.is_none_or(|row| {
            row.electrical_exposure != Energy(10)
                || row.integrity_after != Integrity(0)
                || !row.pending_destruction
        })
        || simulation.enemies().get(enemy_id).is_none()
        || simulation.wire_signal_state(wire).is_none()
    {
        return Err(RuntimeFailure::at(S1m4RuntimeStage::MutualLethalTick));
    }

    let removed = step_commands(&mut simulation, vec![])?;
    record_step(&mut trace, &removed);
    let mut expected = vec![enemy_id.entity_id(), wire.entity_id()];
    expected.sort_unstable();
    if removed
        .destructions
        .iter()
        .map(|row| row.target)
        .collect::<Vec<_>>()
        != expected
        || removed
            .destructions
            .iter()
            .any(|row| row.kind != DestructionKind::Damage)
        || simulation.enemies().get(enemy_id).is_some()
        || simulation.wire_signal_state(wire).is_some()
    {
        return Err(RuntimeFailure::at(S1m4RuntimeStage::MutualLethalRemoval));
    }
    Ok(trace)
}

fn run_hostile_frame_runtime() -> Result<RuntimeTrace, RuntimeFailure> {
    let control = run_hostile_frame_variant(false)?;
    let hostile = run_hostile_frame_variant(true)?;

    let mut control_power = control.power.clone();
    let mut hostile_power = hostile.power.clone();
    control_power.sense.clear();
    hostile_power.sense.clear();
    let common_prefix =
        control
            .trace
            .state_hashes
            .len()
            .checked_sub(1)
            .ok_or(RuntimeFailure::at(
                S1m4RuntimeStage::HostileFrameSensingOnly,
            ))?;
    if control.trace.state_hashes.len() != hostile.trace.state_hashes.len()
        || control.wire != hostile.wire
        || control.sensed
        || !hostile.sensed
        || control.live != hostile.live
        || control.live.granted.0 == 0
        || control.remainder != hostile.remainder
        || control.remainder.energy.0 == 0
        || control.remainder.energy.0 != control.live.granted.0
        || control_power != hostile_power
        || control.enemy != hostile.enemy
        || control.wire_signal != hostile.wire_signal
        || !same_non_sense_snapshot(&control.snapshot, &hostile.snapshot)
        || !same_wire_senses_except_target(&control.wire_senses, &hostile.wire_senses, control.wire)
        || control.trace.state_hashes[..common_prefix]
            != hostile.trace.state_hashes[..common_prefix]
        || control.trace.state_hashes[common_prefix] == hostile.trace.state_hashes[common_prefix]
    {
        return Err(RuntimeFailure::at(
            S1m4RuntimeStage::HostileFrameSensingOnly,
        ));
    }

    let mut trace = control.trace;
    trace.steps += hostile.trace.steps;
    trace.state_hashes.extend(hostile.trace.state_hashes);
    Ok(trace)
}

#[derive(Clone, Debug)]
struct HostileFrameOutcome {
    trace: RuntimeTrace,
    wire: WireId,
    sensed: bool,
    live: aon_sim::PowerLoadReport,
    remainder: aon_sim::InteractionHeatReport,
    power: aon_sim::PowerStepReport,
    enemy: aon_sim::EnemyState,
    wire_signal: aon_sim::WireSignalSnapshot,
    wire_senses: Vec<(WireId, aon_sim::WireSenseSnapshot)>,
    snapshot: aon_sim::RenderSnapshot,
}

fn run_hostile_frame_variant(with_hostile: bool) -> Result<HostileFrameOutcome, RuntimeFailure> {
    let mut simulation = Simulation::new(s1m4_package(
        "s1m4-fuzz-hostile-sensing-only",
        Some((wu(-1, 5), 500)),
        vec![enemy(wu(100, 100))],
        |balance| {
            if let Some(probe) = balance.contact_damage_probe.as_mut() {
                probe.live_energy_per_strength_wu =
                    Rational::new(1, 260).expect("bounded exact coefficient");
                probe.world_leak_weight = 2;
                probe.safe_temperature = Fixed(1_000 * WU);
            }
        },
    )?)
    .map_err(|_| RuntimeFailure::at(S1m4RuntimeStage::Simulation))?;
    let source = simulation
        .power_sources()
        .next()
        .map(|state| state.id())
        .ok_or(RuntimeFailure::at(S1m4RuntimeStage::Simulation))?;
    let mut trace = RuntimeTrace {
        state_hashes: Vec::new(),
        steps: 0,
    };
    let substrate = step_commands(
        &mut simulation,
        vec![Command::PlaceFixedSubstrate(PlaceFixedSubstrateCommand {
            origin: point(0, 0),
            routing_area: large_bounds(),
            footprint: large_bounds(),
        })],
    )?;
    record_step(&mut trace, &substrate);
    let substrate = created_entity(&substrate, 0)?;
    let gate = step_commands(
        &mut simulation,
        vec![Command::PlaceGate(PlaceGateCommand {
            gate_type: GateType::Not,
            origin: point(0, 0),
            routing_domain: RoutingDomain::FixedSubstrate(substrate),
        })],
    )?;
    record_step(&mut trace, &gate);
    let gate = GateId(created_entity(&gate, 0)?);
    let power = step_commands(
        &mut simulation,
        vec![Command::PlaceWire(PlaceWireCommand {
            routing_domain: RoutingDomain::FixedSubstrate(substrate),
            points: vec![wu(-1, 5), wu(-1, -1), wu(0, -1), point(0, -CIRCUIT_PITCH)],
            endpoint_a: EndpointTarget::PowerSourceAnchor(source),
            endpoint_b: gate_power(gate),
        })],
    )?;
    record_step(&mut trace, &power);
    let mut settled = false;
    for _ in 0..16 {
        if simulation
            .gate_signal_state(gate)
            .is_some_and(|state| state.current_output == LogicLevel::High)
        {
            settled = true;
            break;
        }
        let report = step_commands(&mut simulation, vec![])?;
        record_step(&mut trace, &report);
    }
    if !settled {
        return Err(RuntimeFailure::at(S1m4RuntimeStage::PrefixStep));
    }

    let armed = step_commands(
        &mut simulation,
        vec![mutual_live_wire_command(substrate, gate, source)],
    )?;
    record_step(&mut trace, &armed);
    let wire = WireId(created_entity(&armed, 0)?);
    let armed_load = armed
        .power
        .as_ref()
        .and_then(|power| power.load(DemandId::new(wire.entity_id(), DemandKind::LiveWire)));
    let armed_remainder = armed
        .interaction_heat
        .iter()
        .filter(|row| {
            row.owner == wire.entity_id() && row.kind == InteractionHeatKind::LiveWireRemainder
        })
        .collect::<Vec<_>>();
    let armed_signal = simulation
        .wire_signal_state(wire)
        .ok_or(RuntimeFailure::at(
            S1m4RuntimeStage::HostileFrameSensingOnly,
        ))?;
    if armed_load.is_none_or(|load| load.granted.0 == 0)
        || armed_remainder.len() != 1
        || armed_remainder[0].energy.0 == 0
        || !armed.contacts.is_empty()
        || !armed.damage.is_empty()
        || armed_signal.active.high == 0
        || armed_signal.active.low != 0
        || armed_signal.active.unknown != 0
        || simulation
            .wire_sense_state(wire)
            .is_none_or(|sense| sense.sampled_presence)
    {
        return Err(RuntimeFailure::at(
            S1m4RuntimeStage::HostileFrameSensingOnly,
        ));
    }

    let inputs = with_hostile
        .then(|| WorldInputEvent::HostileFrame {
            target_tick: simulation.next_tick(),
            hostiles: vec![HostileCollider {
                id: 1,
                center: wu(1, 5),
                radius: Fixed::ZERO,
            }],
        })
        .into_iter()
        .collect::<Vec<_>>();
    let report = simulation
        .step_with_world_inputs(&[], &inputs)
        .map_err(|_| RuntimeFailure::at(S1m4RuntimeStage::HostileFrameSensingOnly))?;
    record_step(&mut trace, &report);
    let sensed = simulation
        .wire_sense_state(wire)
        .is_some_and(|state| state.sampled_presence);
    let power = report.power.clone().ok_or(RuntimeFailure::at(
        S1m4RuntimeStage::HostileFrameSensingOnly,
    ))?;
    let live = power
        .load(DemandId::new(wire.entity_id(), DemandKind::LiveWire))
        .cloned()
        .ok_or(RuntimeFailure::at(
            S1m4RuntimeStage::HostileFrameSensingOnly,
        ))?;
    let remainders = report
        .interaction_heat
        .iter()
        .filter(|row| {
            row.owner == wire.entity_id() && row.kind == InteractionHeatKind::LiveWireRemainder
        })
        .copied()
        .collect::<Vec<_>>();
    if live.granted.0 == 0
        || remainders.len() != 1
        || remainders[0].energy.0 == 0
        || remainders[0].energy.0 != live.granted.0
        || !report.contacts.is_empty()
        || !report.damage.is_empty()
        || !report.destructions.is_empty()
    {
        return Err(RuntimeFailure::at(
            S1m4RuntimeStage::HostileFrameSensingOnly,
        ));
    }
    let enemy = simulation
        .enemies()
        .iter()
        .next()
        .copied()
        .ok_or(RuntimeFailure::at(
            S1m4RuntimeStage::HostileFrameSensingOnly,
        ))?;
    let wire_signal = simulation
        .wire_signal_state(wire)
        .ok_or(RuntimeFailure::at(
            S1m4RuntimeStage::HostileFrameSensingOnly,
        ))?;
    let mut snapshot = aon_sim::RenderSnapshot::default();
    simulation.write_render_snapshot(&mut snapshot);
    let wire_senses = snapshot
        .wires()
        .iter()
        .map(|row| {
            simulation
                .wire_sense_state(row.id)
                .map(|sense| (row.id, sense))
                .ok_or(RuntimeFailure::at(
                    S1m4RuntimeStage::HostileFrameSensingOnly,
                ))
        })
        .collect::<Result<Vec<_>, _>>()?;
    Ok(HostileFrameOutcome {
        trace,
        wire,
        sensed,
        live,
        remainder: remainders[0],
        power,
        enemy,
        wire_signal,
        wire_senses,
        snapshot,
    })
}

fn same_wire_senses_except_target(
    control: &[(WireId, aon_sim::WireSenseSnapshot)],
    hostile: &[(WireId, aon_sim::WireSenseSnapshot)],
    target: WireId,
) -> bool {
    control.len() == hostile.len()
        && control.iter().zip(hostile).all(|(control, hostile)| {
            if control.0 != hostile.0 {
                return false;
            }
            if control.0 == target {
                control.1.ports == hostile.1.ports
                    && !control.1.sampled_presence
                    && hostile.1.sampled_presence
                    && control.1.intended_level == LogicLevel::Low
                    && hostile.1.intended_level == LogicLevel::High
                    && control.1.intended_strength == hostile.1.intended_strength
                    && control.1.intended_strength.0 > 0
            } else {
                control == hostile
            }
        })
}

fn same_non_sense_snapshot(
    control: &aon_sim::RenderSnapshot,
    hostile: &aon_sim::RenderSnapshot,
) -> bool {
    control.scenario_id() == hostile.scenario_id()
        && control.next_tick() == hostile.next_tick()
        && control.topology_revision() == hostile.topology_revision()
        && control.contract() == hostile.contract()
        && control.primitive_count() == hostile.primitive_count()
        && control.main_core() == hostile.main_core()
        && control.fixed_substrates() == hostile.fixed_substrates()
        && control.mobiles() == hostile.mobiles()
        && control.gates() == hostile.gates()
        && control.wires() == hostile.wires()
        && control.junctions() == hostile.junctions()
        && control.enemies() == hostile.enemies()
        && control.construction_sites() == hostile.construction_sites()
        && control.run_status() == hostile.run_status()
}

fn run_two_tick_thermal_runtime() -> Result<RuntimeTrace, RuntimeFailure> {
    const SAFE_TEMPERATURE_WU: u64 = 100;

    let mut simulation = Simulation::new(s1m4_package(
        "s1m4-fuzz-two-tick-thermal",
        Some((wu(-1, 5), 10_000)),
        vec![enemy(wu(100, 100))],
        |balance| {
            if let Some(probe) = balance.contact_damage_probe.as_mut() {
                probe.live_energy_per_strength_wu =
                    Rational::new(1, 1).expect("bounded exact coefficient");
                probe.world_leak_weight = 2;
                probe.thermal_capacity.wire = 1;
                probe.safe_temperature =
                    Fixed(i64::try_from(SAFE_TEMPERATURE_WU).expect("small bound") * WU);
                probe.thermal_damage_rate = Rational::new(1, 1).expect("bounded exact coefficient");
            }
        },
    )?)
    .map_err(|_| RuntimeFailure::at(S1m4RuntimeStage::Simulation))?;
    let source = simulation
        .power_sources()
        .next()
        .map(|state| state.id())
        .ok_or(RuntimeFailure::at(S1m4RuntimeStage::Simulation))?;
    let mut trace = RuntimeTrace {
        state_hashes: Vec::new(),
        steps: 0,
    };
    let substrate = step_commands(
        &mut simulation,
        vec![Command::PlaceFixedSubstrate(PlaceFixedSubstrateCommand {
            origin: point(0, 0),
            routing_area: large_bounds(),
            footprint: large_bounds(),
        })],
    )?;
    record_step(&mut trace, &substrate);
    let substrate = created_entity(&substrate, 0)?;
    let gate = step_commands(
        &mut simulation,
        vec![Command::PlaceGate(PlaceGateCommand {
            gate_type: GateType::Not,
            origin: point(0, 0),
            routing_domain: RoutingDomain::FixedSubstrate(substrate),
        })],
    )?;
    record_step(&mut trace, &gate);
    let gate = GateId(created_entity(&gate, 0)?);
    let power = step_commands(
        &mut simulation,
        vec![Command::PlaceWire(PlaceWireCommand {
            routing_domain: RoutingDomain::FixedSubstrate(substrate),
            points: vec![wu(-1, 5), wu(-1, -1), wu(0, -1), point(0, -CIRCUIT_PITCH)],
            endpoint_a: EndpointTarget::PowerSourceAnchor(source),
            endpoint_b: gate_power(gate),
        })],
    )?;
    record_step(&mut trace, &power);
    let mut settled = false;
    for _ in 0..16 {
        if simulation
            .gate_signal_state(gate)
            .is_some_and(|state| state.current_output == LogicLevel::High)
        {
            settled = true;
            break;
        }
        let report = step_commands(&mut simulation, vec![])?;
        record_step(&mut trace, &report);
    }
    if !settled {
        return Err(RuntimeFailure::at(S1m4RuntimeStage::PrefixStep));
    }

    let heated = step_commands(
        &mut simulation,
        vec![mutual_live_wire_command(substrate, gate, source)],
    )?;
    record_step(&mut trace, &heated);
    let wire = WireId(created_entity(&heated, 0)?);
    let live = heated
        .power
        .as_ref()
        .and_then(|power| power.load(DemandId::new(wire.entity_id(), DemandKind::LiveWire)))
        .ok_or(RuntimeFailure::at(S1m4RuntimeStage::ThermalHeatLoad))?;
    let remainders = heated
        .interaction_heat
        .iter()
        .filter(|row| {
            row.owner == wire.entity_id() && row.kind == InteractionHeatKind::LiveWireRemainder
        })
        .collect::<Vec<_>>();
    let remainder_heat = remainders
        .first()
        .map(|row| row.energy)
        .ok_or(RuntimeFailure::at(S1m4RuntimeStage::ThermalHeatReport))?;
    let interaction_heat = heated
        .interaction_heat
        .iter()
        .filter(|row| row.owner == wire.entity_id())
        .try_fold(0_u64, |sum, row| sum.checked_add(row.energy.0))
        .ok_or(RuntimeFailure::at(S1m4RuntimeStage::ThermalHeatReport))?;
    let power_heat = heated
        .power
        .as_ref()
        .into_iter()
        .flat_map(|power| power.heat_contributions.iter())
        .filter(|row| row.owner == wire)
        .try_fold(0_u64, |sum, row| sum.checked_add(row.energy.0))
        .ok_or(RuntimeFailure::at(S1m4RuntimeStage::ThermalHeatReport))?;
    let expected_integrated_heat = interaction_heat
        .checked_add(power_heat)
        .map(HeatEnergy)
        .ok_or(RuntimeFailure::at(S1m4RuntimeStage::ThermalHeatReport))?;
    let analyzer = simulation
        .construction_contact_damage_analyzer_snapshot()
        .map_err(|_| RuntimeFailure::at(S1m4RuntimeStage::ThermalHeatState))?
        .ok_or(RuntimeFailure::at(S1m4RuntimeStage::ThermalHeatState))?;
    let wire_after_heat = analyzer
        .damage
        .iter()
        .find(|row| row.target == wire.entity_id())
        .ok_or(RuntimeFailure::at(S1m4RuntimeStage::ThermalHeatState))?;
    let expected_temperature = i64::try_from(expected_integrated_heat.0)
        .ok()
        .and_then(|heat| heat.checked_mul(WU))
        .map(Fixed)
        .ok_or(RuntimeFailure::at(S1m4RuntimeStage::ThermalHeatState))?;
    if expected_integrated_heat.0 <= SAFE_TEMPERATURE_WU + 10
        || remainders.len() != 1
        || remainder_heat.0 != live.granted.0
        || heated
            .damage
            .iter()
            .any(|row| row.target == wire.entity_id())
    {
        return Err(RuntimeFailure::at(S1m4RuntimeStage::ThermalHeatReport));
    }
    if wire_after_heat.integrity != Integrity(10)
        || wire_after_heat.heat_energy != expected_integrated_heat
        || wire_after_heat.temperature != expected_temperature
    {
        return Err(RuntimeFailure::at(S1m4RuntimeStage::ThermalHeatState));
    }

    let damaged = step_commands(&mut simulation, vec![])?;
    record_step(&mut trace, &damaged);
    let expected_damage = expected_integrated_heat
        .0
        .checked_sub(SAFE_TEMPERATURE_WU)
        .map(Integrity)
        .ok_or(RuntimeFailure::at(S1m4RuntimeStage::ThermalNextTickDamage))?;
    let rows = damaged
        .damage
        .iter()
        .filter(|row| row.target == wire.entity_id())
        .collect::<Vec<_>>();
    if rows.len() != 1
        || rows[0].electrical_exposure != Energy(0)
        || rows[0].electrical_damage != Integrity(0)
        || rows[0].thermal_damage != expected_damage
        || rows[0].integrity_before != Integrity(10)
        || rows[0].integrity_after != Integrity(0)
        || !rows[0].pending_destruction
        || !damaged.contacts.is_empty()
        || !damaged.destructions.is_empty()
    {
        return Err(RuntimeFailure::at(S1m4RuntimeStage::ThermalNextTickDamage));
    }
    Ok(trace)
}

fn mutual_live_wire_command(
    substrate: EntityId,
    gate: GateId,
    source: aon_sim::PowerSourceId,
) -> Command {
    Command::PlaceWire(PlaceWireCommand {
        routing_domain: RoutingDomain::FixedSubstrate(substrate),
        points: vec![
            wu(-1, 5),
            point(-WU, 9 * WU + 2 * CIRCUIT_PITCH),
            point(0, 9 * WU + 2 * CIRCUIT_PITCH),
            wu(0, 5),
            point(3 * WU + CIRCUIT_PITCH, 5 * WU),
            point(CIRCUIT_PITCH, 0),
        ],
        endpoint_a: EndpointTarget::PowerSourceAnchor(source),
        endpoint_b: gate_output(gate),
    })
}

fn s1m4_package(
    scenario_id: &'static str,
    source: Option<(FixedVec2, u64)>,
    enemies: Vec<EnemyInitialState>,
    mutate: impl FnOnce(&mut BalanceProfile),
) -> Result<SimulationPackage, RuntimeFailure> {
    let mut balance =
        BalanceProfile::construction_contact_damage_alpha(format!("balance-{scenario_id}"));
    mutate(&mut balance);
    let profiles = ProfileBundle {
        numeric: NumericProfile::reference_v1(format!("numeric-{scenario_id}")),
        physical_scale: PhysicalScaleProfile::stage0_alpha(format!("physical-{scenario_id}")),
        balance,
    };
    let contract = SimulationContract::from_profiles(&profiles)
        .map_err(|_| RuntimeFailure::at(S1m4RuntimeStage::Profile))?;
    Ok(SimulationPackage::new(
        scenario_id,
        InitialWorld::MainCorePowerEnemyV1 {
            main_core_position: wu(-100, -100),
            main_core_integrity: Integrity(100),
            main_core_heat_energy: HeatEnergy(0),
            power_sources: source
                .into_iter()
                .map(|(position, generation)| {
                    PowerSourceInitialState::new(position, Energy(generation))
                })
                .collect(),
            enemies,
        },
        StageFeatureSet {
            signal: true,
            mobility: true,
            capacity: true,
            sensing: true,
            power: true,
            construction: true,
            contact: true,
            damage: true,
            ..StageFeatureSet::none()
        },
        contract,
        profiles,
    ))
}

fn step_commands(
    simulation: &mut Simulation,
    commands: Vec<Command>,
) -> Result<aon_sim::StepReport, RuntimeFailure> {
    let envelopes = commands
        .into_iter()
        .enumerate()
        .map(|(ordinal, command)| CommandEnvelope {
            target_tick: simulation.next_tick(),
            ordinal: u64::try_from(ordinal).unwrap_or(u64::MAX),
            command,
        })
        .collect::<Vec<_>>();
    let report = simulation
        .step(&envelopes)
        .map_err(|_| RuntimeFailure::at(S1m4RuntimeStage::PrefixStep))?;
    if !report.command_rejections.is_empty() || report.command_acceptances.len() != envelopes.len()
    {
        return Err(RuntimeFailure::at(S1m4RuntimeStage::CommandAcceptance));
    }
    Ok(report)
}

fn created_entity(report: &aon_sim::StepReport, index: usize) -> Result<EntityId, RuntimeFailure> {
    report
        .command_acceptances
        .get(index)
        .and_then(|row| row.created_entity)
        .ok_or(RuntimeFailure::at(S1m4RuntimeStage::CommandAcceptance))
}

fn record_step(trace: &mut RuntimeTrace, report: &aon_sim::StepReport) {
    trace.state_hashes.push(report.state_hash);
    trace.steps += 1;
}

const fn gate_output(gate: GateId) -> EndpointTarget {
    EndpointTarget::GatePort(GatePortRef {
        gate,
        port: GatePort::Output,
    })
}

const fn gate_input(gate: GateId) -> EndpointTarget {
    EndpointTarget::GatePort(GatePortRef {
        gate,
        port: GatePort::InputA,
    })
}

const fn gate_power(gate: GateId) -> EndpointTarget {
    EndpointTarget::GatePort(GatePortRef {
        gate,
        port: GatePort::Power,
    })
}

const fn point(x: i64, y: i64) -> FixedVec2 {
    FixedVec2::new(Fixed(x), Fixed(y))
}

const fn wu(x: i64, y: i64) -> FixedVec2 {
    point(x * WU, y * WU)
}

const fn enemy(position: FixedVec2) -> EnemyInitialState {
    EnemyInitialState::new(
        position,
        point(0, 0),
        Fixed(ENEMY_RADIUS),
        Integrity(10),
        HeatEnergy(0),
    )
}

const fn large_bounds() -> FixedAabb {
    FixedAabb::new(wu(-32, -32), wu(32, 32))
}

const fn mobile_bounds() -> FixedAabb {
    FixedAabb::new(wu(-1, -1), wu(1, 1))
}

struct CyclicBytes<'a> {
    bytes: &'a [u8],
    cursor: usize,
}

impl<'a> CyclicBytes<'a> {
    const fn new(bytes: &'a [u8]) -> Self {
        Self { bytes, cursor: 0 }
    }

    fn next_u8(&mut self) -> u8 {
        if self.bytes.is_empty() {
            return 0;
        }
        let value = self.bytes[self.cursor % self.bytes.len()];
        self.cursor += 1;
        value
    }
}
